/* 目標レベルマスタ */
CREATE TABLE IF NOT EXISTS goal_levels (
	id INT PRIMARY KEY
  , level_code VARCHAR(20) NOT NULL UNIQUE
  , display_order INT NOT NULL
  , enabled BOOLEAN NOT NULL DEFAULT TRUE
);

/* ユーザーマスタ */
CREATE TABLE IF NOT EXISTS users (
	user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  , e164_phone_number VARCHAR(16) NOT NULL UNIQUE
  , user_name VARCHAR(50)
  , password VARCHAR(100)
  , goal_level_id INT
  , role VARCHAR(50)
  , created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  , updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  
  , CONSTRAINT fk_users_goal_level
  		FOREIGN KEY (goal_level_id)
  		REFERENCES goal_levels(id)
);

/* 予約マスタ */
CREATE TABLE IF NOT EXISTS reservations (
	reservation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  , user_id BIGINT NOT NULL
  , starts_at TIMESTAMP NOT NULL
  , ends_at TIMESTAMP NOT NULL
  , created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  , updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  
  , CONSTRAINT fk_reservation_user
  		FOREIGN KEY (user_id)
  		REFERENCES users(user_id)
  
  , CONSTRAINT chk_reservations_time
  		CHECK (ends_at > starts_at)
);